import { characteristic } from '@/mock/mock';
import type { HostileCreatures } from './types';
import type { Location } from '../locations/types';

export const raidBossMock: HostileCreatures[] = [
  {
    id: 1,
    name: 'Ледяной Клык',
    src: 'https://i.pinimg.com/736x/ad/46/e8/ad46e81fbde3281cc6350aa34cea57bf.jpg',
    type: 'raidBoss',
    status: 'Жив',
    shortDescription: 'Гигантский ледяной дракон терроризирует северные долины.',
    mdDescription: 'Гигантский ледяной дракон терроризирует северные долины.',
    mdHistory: 'Появился после Великой зимы в Нордланде.',
    mdFunFacts: 'Летом спит в кристальных пещерах.',
    mdStatblock: 'Ледяной Клык — легендарное существо, которого боятся все ближайшие поселения.',
    locationIds: [1, 2],
    locations: [
      { id: 1, name: 'Долина Гурван-Гол', shortDescription: '', src: '' },
      { id: 2, name: 'Горы Морозного Пика', shortDescription: '', src: '' },
    ],
    sizeId: 'large',
    typeId: 1,
    hp: '350',
    armorClass: 18,
    speed: '40 футов',
    characteristicIds: [
      { id: 'strength', value: '18' },
      { id: 'dexterity', value: '12' },
      { id: 'constitution', value: '16' },
    ],
    savingThrows: 'STR +8, DEX +3, CON +6',
    skills: 'Восприятие +8, Скрытность +2',
    damageImmunities: [1, 2],
    conditionImmunities: [1],
    damageResistance: [3],
    conditionResistance: [2],
    senses: 'Тёмное зрение 120 футов, пассивное восприятие 18',
    language: 'русский',
    challenge: 17,
    proficiencyBonus: 6,
  },
  {
    id: 2,
    name: 'Огненный Колосс',
    src: 'https://i.pinimg.com/736x/ad/46/e8/ad46e81fbde3281cc6350aa34cea57bf.jpg',
    type: 'raidBoss',
    status: 'Жив',
    shortDescription: 'Гигантский элементаль огня и магмы.',
    mdDescription: 'Гигантский элементаль огня и магмы.',
    mdHistory: 'Возник после извержения вулкана несколько столетий назад.',
    mdFunFacts: 'При ходьбе вызывает мини-землетрясения.',
    mdStatblock: 'Огненный Колосс выходит из вулкана, разрушая всё на своём пути.',
    locationIds: [3],
    locations: [{ id: 3, name: 'Вулканический кратер', shortDescription: '', src: '' }],
    sizeId: 'huge',
    typeId: 2,
    hp: '420',
    armorClass: 20,
    speed: '30 футов',
    characteristicIds: [
      { id: 'strength', value: '20' },
      { id: 'constitution', value: '18' },
    ],
    savingThrows: 'STR +9, CON +7',
    skills: 'Запугивание +6, Атлетика +12',
    damageImmunities: [3],
    conditionImmunities: [2, 3],
    damageResistance: [4, 5],
    conditionResistance: [1],
    senses: 'Слепое чутьё 60 футов, Тёмное зрение 120 футов, пассивное восприятие 20',
    language: 'не русский',
    challenge: 18,
    proficiencyBonus: 6,
  },
];
