import type { NPC } from './types';

export const npcData: NPC[] = [
  {
    id: 1,
    name: 'Thoren Blackleaf',
    src: 'https://img.freepik.com/free-photo/fantasy-group-adventurers_23-2151470674.jpg',
    status: 'Жив',
    fraction: 'Гильдия Теней',
    md_description: `### Биография
Thoren Blackleaf — мастер скрытности и стратегических манёвров. С детства обучался в гильдии воров, где совершенствовал свои навыки: от лазания по крышам до тихого открывания замков. Его способности позволяли ему оставаться незамеченным даже среди хорошо охраняемых замков.

### Характер
Thoren — человек контрастов. С одной стороны, он хладнокровен и расчетлив, с другой — верен своим друзьям и готов помочь невинным. Любит наблюдать за природой и изучать растения, что помогает ему в приготовлении зелий и ядов.`,
    md_short_description: 'Мастер скрытности и стратегических манёвров из Гильдии Теней.',
    md_history:
      'Вырос в скрытом анклаве воров, где освоил искусство скрытности и ловкости. Со временем стал мастером шпионажа и незаметного передвижения, известным даже в соседних королевствах.',
    md_fun_facts: 'Ночью любит играть на флейте и собирать редкие травы.',
    language: 'Russian',
    country_ids: [1],
    country_data: [{ id: 1, name: 'Нордланд' }],
    location_ids: [1, 2],
    location_data: [
      { id: 1, name: 'Долина Гурван-Гол' },
      { id: 2, name: 'Горы Морозного Пика' },
    ],
  },
  {
    id: 2,
    name: 'Eldira Sunmist',
    src: 'https://i.pinimg.com/736x/f1/ad/ef/f1adef87d089ec0e8569259242a0a982.jpg',
    status: 'Deceased',
    fraction: 'Circle of Mages',
    md_description: 'An elf mage who studied the stars.',
    md_short_description: 'Эльфийская магесса, исследующая звёзды.',
    md_history: 'Her knowledge of celestial magic saved her kingdom multiple times.',
    md_fun_facts: 'Had a pet owl named Lumen.',
    language: 'Russian',
    country_ids: [2],
    country_data: [{ id: 2, name: 'Elvaria' }],
    location_ids: [3],
    location_data: [{ id: 3, name: 'Crystal Lake' }],
  },
  {
    id: 3,
    name: 'Borin Ironfist',
    src: 'https://i.pinimg.com/1200x/93/01/33/93013399268cd83136e7fcc20294fae2.jpg',
    status: 'Alive',
    fraction: 'Dwarven Clan Hammerstone',
    md_description: 'A dwarven warrior known for his strength and loyalty.',
    md_short_description: 'Сильный и верный дворф воин.',
    md_history: 'Fought in the Great Battle of Stonehold.',
    md_fun_facts: 'Brews his own ale and enters competitions every year.',
    language: 'Russian',
    country_ids: [3],
    country_data: [{ id: 3, name: 'Stonehelm' }],
    location_ids: [4],
    location_data: [{ id: 4, name: 'Stoneforge Keep' }],
  },
  {
    id: 4,
    name: 'Lyria Moonshadow',
    src: 'https://i.pinimg.com/1200x/55/13/37/551337bc0711b554324d5d51dd9e24da.jpg',
    status: 'Alive',
    fraction: 'Elven Rangers',
    md_description: 'A scout and tracker, protector of the enchanted forests.',
    md_short_description: 'Следопыт и защитник волшебных лесов.',
    md_history: 'Served the High Elves as a messenger and spy.',
    md_fun_facts: 'Can communicate with animals.',
    language: 'Russian',
    country_ids: [2],
    country_data: [{ id: 2, name: 'Elvaria' }],
    location_ids: [5],
    location_data: [{ id: 5, name: 'Silverleaf Woods' }],
  },
  {
    id: 5,
    name: 'Garrick Stonebreaker',
    src: 'https://i.pinimg.com/1200x/86/cb/ae/86cbaea2b3bc3ee164c4aea6f099104e.jpg',
    status: 'Alive',
    fraction: 'Mercenaries Guild',
    md_description: 'A brute mercenary who takes on dangerous jobs.',
    md_short_description: 'Наёмник, выполняющий опасные задания.',
    md_history: 'Traveled across many lands seeking fortune.',
    md_fun_facts: 'Collects rare weapons from defeated foes.',
    language: 'Russian',
    country_ids: [3],
    country_data: [{ id: 3, name: 'Stonehelm' }],
    location_ids: [4, 6],
    location_data: [
      { id: 4, name: 'Stoneforge Keep' },
      { id: 6, name: 'Ironvale Pass' },
    ],
  },
];
