import { characteristic } from '@/mock/mock';
import type { RaidBoss } from './types';

export const raidBossMock: RaidBoss[] = [
  {
    id: 1,
    name: 'Ледяной Клык',
    src: 'https://i.pinimg.com/736x/ad/46/e8/ad46e81fbde3281cc6350aa34cea57bf.jpg',
    status: 'Жив',
    md_short_description: 'Гигантский ледяной дракон терроризирует северные долины.',
    md_description: 'Гигантский ледяной дракон терроризирует северные долины.',
    md_history: 'Появился после Великой зимы в Нордланде.',
    md_fun_facts: 'Летом спит в кристальных пещерах.',
    location_ids: [1, 2],
    location_data: [
      { id: 1, name: 'Долина Гурван-Гол' },
      { id: 2, name: 'Горы Морозного Пика' },
    ],
    size_id: 'large',
    type_id: 1,
    hp: '350',
    speed: '40 футов',
    characteristic_ids: ['strength', 'dexterity', 'constitution'],
    characteristic_data: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    saving_throws: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    skills: 'Восприятие +8, Скрытность +2',
    damage_immunities: [1, 2],
    condition_immunities: [1],
    damage_resistance: [3],
    condition_resistance: [2],
    senses: 'Тёмное зрение 120 футов, пассивное восприятие 18',
    language: 'русский',
    challenge: 17,
    proficiency_bonus: 6,
    md_content: 'Ледяной Клык — легендарное существо, которого боятся все ближайшие поселения.',
  },
  {
    id: 2,
    name: 'Огненный Колосс',
    src: 'https://i.pinimg.com/736x/ad/46/e8/ad46e81fbde3281cc6350aa34cea57bf.jpg',
    status: 'Жив',
    md_short_description: 'Гигантский элементаль огня и магмы.',
    md_description: 'Гигантский элементаль огня и магмы.',
    md_history: 'Возник после извержения вулкана несколько столетий назад.',
    md_fun_facts: 'При ходьбе вызывает мини-землетрясения.',
    location_ids: [3],
    location_data: [{ id: 3, name: 'Вулканический кратер' }],
    size_id: 'huge',
    type_id: 2,
    hp: '420',
    speed: '30 футов',
    characteristic_ids: ['strength', 'constitution'],
    characteristic_data: characteristic.filter((c) => ['strength', 'constitution'].includes(c.id)),
    saving_throws: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    skills: 'Запугивание +6, Атлетика +12',
    damage_immunities: [3],
    condition_immunities: [2, 3],
    damage_resistance: [4, 5],
    condition_resistance: [1],
    senses: 'Слепое чутьё 60 футов, Тёмное зрение 120 футов, пассивное восприятие 20',
    language: 'не русский',
    challenge: 18,
    proficiency_bonus: 6,
    md_content: 'Огненный Колосс выходит из вулкана, разрушая всё на своём пути.',
  },
  {
    id: 3,
    name: 'Громокрылый Рок',
    src: 'https://i.pinimg.com/736x/45/42/d9/4542d9b6dfac380fbeca3b78669f6437.jpg',
    status: 'Жив',
    md_short_description: 'Огромная птица, управляющая штормами.',
    md_description: 'Огромная птица, управляющая штормами.',
    md_history: 'Гнездится на самых высоких скалах.',
    md_fun_facts: 'Её перья могут создавать молнии.',
    location_ids: [2, 4],
    location_data: [
      { id: 2, name: 'Горы Морозного Пика' },
      { id: 4, name: 'Скалы Небесного Пика' },
    ],
    size_id: 'gargantuan',
    type_id: 3,
    hp: '480',
    speed: '80 футов, Полёт 120 футов',
    characteristic_ids: ['strength', 'dexterity'],
    characteristic_data: characteristic.filter((c) => ['strength', 'dexterity'].includes(c.id)),
    saving_throws: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    skills: 'Восприятие +10, Акробатика +7',
    damage_immunities: [],
    condition_immunities: [2],
    damage_resistance: [3, 4],
    condition_resistance: [1, 2],
    senses: 'Тёмное зрение 120 футов, пассивное восприятие 22',
    language: 'русский',
    challenge: 19,
    proficiency_bonus: 6,
    md_content: 'Громокрылый Рок господствует в небе, управляя погодой и молниями.',
  },
  {
    id: 4,
    name: 'Пещерная Гидра',
    src: 'https://i.pinimg.com/1200x/b7/ee/ad/b7eeadd5cf5fec16b5504ea6325755ed.jpg',
    status: 'Жив',
    md_short_description: 'Многоголовая змея, обитающая в подземных пещерах.',
    md_description: 'Многоголовая змея, обитающая в подземных пещерах.',
    md_history: 'Известна своими засадами на искателей сокровищ.',
    md_fun_facts: 'Каждая голова регенерируется, если её отрубить.',
    location_ids: [5],
    location_data: [{ id: 5, name: 'Чёрные каменные пещеры' }],
    size_id: 'huge',
    type_id: 4,
    hp: '400',
    speed: '30 футов, Плавание 40 футов',
    characteristic_ids: ['strength', 'constitution'],
    characteristic_data: characteristic.filter((c) => ['strength', 'constitution'].includes(c.id)),
    saving_throws: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    skills: 'Восприятие +6, Скрытность +5',
    damage_immunities: [],
    condition_immunities: [],
    damage_resistance: [2, 3],
    condition_resistance: [],
    senses: 'Тёмное зрение 60 футов, Чуткость 60 футов',
    language: 'не русский',
    challenge: 16,
    proficiency_bonus: 5,
    md_content: 'Пещерная Гидра охраняет сокровища глубин гор.',
  },
  {
    id: 5,
    name: 'Ядовитый Клык',
    src: 'https://i.pinimg.com/736x/1c/2e/3b/1c2e3b899b0a7c69be80f26aef554827.jpg',
    status: 'Жив',
    md_short_description: 'Ядовитая змея, обитающая в болотах.',
    md_description: 'Ядовитая змея, обитающая в болотах.',
    md_history: 'Сеет страх среди деревенских жителей.',
    md_fun_facts: 'Её яд светится в лунном свете.',
    location_ids: [6],
    location_data: [{ id: 6, name: 'Болота Мерсмир' }],
    size_id: 'large',
    type_id: 5,
    hp: '220',
    speed: '40 футов, Плавание 30 футов',
    characteristic_ids: ['dexterity', 'constitution'],
    characteristic_data: characteristic.filter((c) => ['dexterity', 'constitution'].includes(c.id)),
    saving_throws: characteristic.filter((c) =>
      ['strength', 'dexterity', 'constitution'].includes(c.id),
    ),
    skills: 'Скрытность +8, Восприятие +5',
    damage_immunities: [],
    condition_immunities: [],
    damage_resistance: [1],
    condition_resistance: [],
    senses: 'Тёмное зрение 60 футов, пассивное восприятие 14',
    language: 'русский',
    challenge: 12,
    proficiency_bonus: 4,
    md_content: 'Ядовитый Клык атакует всё, что приближается к его болоту.',
  },
];
